### ISSUE TITLE
Handle IDE project files in the repo

### ISSUE THREAD

**Issue by jahudzik** [MFlisar/Multiples#3]
There's a number of .idea/*.xml files auto-generated by Intellij. Decide if you want to keep them in the repository or add to ignore list. ([more](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems))

**Comment by MFlisar** [comment]
I'll remove them

**Comment by MFlisar** [comment]
Sorry, I can't find any idea or xml files in the repo, can you show me what you mean? Or do you just mean the `.gitignore` file itself?

**Comment by jahudzik** [comment]
I meant unversioned XML files in the .idea directory. If not present there, they are generated by Intellij. Adding the .idea directory to thie .gitignore (as you did) is fine for me.
